### ISSUE TITLE
I got the error "Unable to parse as YAML or JSON"

### ISSUE THREAD

**Issue by YousufSSyed** [dustinksi/obsidian-sync-calendar#4]
![Screenshot 2023-05-08 at 2 41 38 AM](https://user-images.githubusercontent.com/42646062/236752782-927a47a0-3d5a-4368-b083-9e24ba023bc6.png)

I followed all the instructions in the readme, I downloaded the JSON file, put it in the `.obsidian` folder, and named it `calendar.sync.credentials.json`:

![Screenshot 2023-05-08 at 2 43 40 AM](https://user-images.githubusercontent.com/42646062/236753410-65ca35db-bb79-4f74-a49f-bd64fc87fa96.png)

I also ran the command `Sync with Calendar`, and restarted Obsidian, but I still got the error with the block:

````
```sync-calendar
name: "{numberTodo} todos @ Apr. 21",
timeMin: "2023-04-21"
timeMax: "2023-04-22"
```
````

**Comment by dustinksi** [comment]
Thanks for using this plugin! 
I noticed that you added a comma in the value of "name" which caused the issue. Removing it should make it work fine. 
You can try using the following code snippet instead. :)
````
```sync-calendar
name: "{numberTodo} todos @ Apr. 21"
timeMin: "2023-04-21"
timeMax: "2023-04-22"
```
````

**Comment by YousufSSyed** [comment]
I see, but it worth noting that I had copied and pasted the block from https://github.com/dustinksi/obsidian-sync-calendar#use-this-plugin, which includes the comma. While I hadn't noticed it at first, I would've thought maybe it was supposed to be there. You should fix that.

**Comment by YousufSSyed** [comment]
Thanks for updating the readme!
