### ISSUE TITLE
Make error messages more specific, like if a field in the sync-calendar block is invalid.

### ISSUE THREAD

**Issue by YousufSSyed** [dustinksi/obsidian-sync-calendar#5]
I wrote another issue: https://github.com/dustinksi/obsidian-sync-calendar/issues/4, where I got the error "Unable to parse as YAML or JSON" when I copied and pasted the sample codeblock from the readme. 

![Screenshot 2023-05-08 at 2 41 38 AM](https://user-images.githubusercontent.com/42646062/236752782-927a47a0-3d5a-4368-b083-9e24ba023bc6.png)

The dev said it was because a comma was there. The error message should've mentioned that instead of giving a vague error message, and one that isn't related or seemingly related to what I wrote in the block. Since it mentions JSON, I thought maybe the `calendar.sync.credentials.json` file was invalid. 

If users don't write the block correctly, it should mention which field is invalid, and ideally, why.

**Comment by dustinksi** [comment]
Thanks for your feedback, it's an extremely valuable suggestion. I have updated the code to provide more specific error messages based on your recommendation. 

**The updated error message will now specify the exact field for invalid YAML, to avoid confusion.**

For example, like the invalid code block:
````
```sync-calendar
name: "{numberTodos} todos @ Apr. 21",
timeMin: "2023-04-21"
timeMax: "2023-04-22"
```
````
, the error message would now be:

<img width="725" alt="Screen Shot 2023-05-10" src="https://github.com/dustinksi/obsidian-sync-calendar/assets/20951128/2cfd00f2-d41d-478c-bb8c-c01d76cf3b8a">

Let me know if you have any other questions or feedback! I appreciate all opportunities to continue enhancing this plugin for users.

**Comment by YousufSSyed** [comment]
Thank you! I really appreciate your swift responses to my feedback!
